[accessibility]
ui_scale = 0.95000000670552254

[backdrop]
enabled = true

[bar.default]
background_opacity = 0.71999998390674591
margin_ends = 0
radius = 0
reserve_space = false
smart_auto_hide = true
start = [ "launcher", "wallpaper", "workspaces", "active_window" ]
thickness = 21

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-2", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1920.0
    cy = 2218.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1418.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0
    cy = 1258.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
polkit_agent = true

    [shell.animation]
    speed = 1.2000000178813934

    [shell.panel]
    transparency_mode = "glass"

[system.monitor]
cpu_poll_seconds = 32
disk_poll_seconds = 46
gpu_poll_seconds = 31
memory_poll_seconds = 35
network_poll_seconds = 48

[theme]
builtin = "Nord"
community_palette = "Oxocarbon"
mode = "light"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/isthatcentered/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/isthatcentered/Pictures/Wallpapers/daniele-colucci--_5dCixJ6FI-unsplash.jpg"

    [wallpaper.last]
    path = "/home/isthatcentered/Pictures/Wallpapers/daniele-colucci--_5dCixJ6FI-unsplash.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/isthatcentered/Pictures/Wallpapers/daniele-colucci--_5dCixJ6FI-unsplash.jpg"
