local VNode = require('nope.ui.VNode')

describe('VNode', function()
  describe('create', function()
    it('creates node with type and props', function()
      local node = VNode.create('text', { text = 'hello' })
      assert.same('text', node.type)
      assert.same({ text = 'hello' }, node.props)
      assert.same({}, node.children)
      assert.same(nil, node.key)
    end)

    it('creates node with children', function()
      local child = VNode.create('text', { text = 'child' })
      local node = VNode.create('stack', {}, { child })
      assert.same(1, #node.children)
      assert.same('text', node.children[1].type)
    end)

    it('creates node with key', function()
      local node = VNode.create('text', {}, {}, 'my-key')
      assert.same('my-key', node.key)
    end)

    it('defaults props to empty table', function()
      local node = VNode.create('text', nil)
      assert.same({}, node.props)
    end)

    it('defaults children to empty table', function()
      local node = VNode.create('text', {}, nil)
      assert.same({}, node.children)
    end)
  end)

  describe('create_instance', function()
    it('creates instance with component and props', function()
      local component = function()
        return VNode.create('text', {})
      end
      local instance = VNode.create_instance(component, { foo = 'bar' })

      assert.same(component, instance.component)
      assert.same({ foo = 'bar' }, instance.props)
      assert.same({}, instance._hooks)
      assert.same(1, instance._hook_index)
      assert.same(false, instance._mounted)
    end)

    it('creates instance with key', function()
      local instance = VNode.create_instance(function() end, {}, 'my-key')
      assert.same('my-key', instance.key)
    end)

    it('initializes empty children table', function()
      local instance = VNode.create_instance(function() end, {})
      assert.same({}, instance._children)
    end)
  end)
end)
